### ISSUE TITLE
CS-576 Re: University of North Florida ILL link broken on Center for Research Libraries database

### ISSUE THREAD

**Issue by AndyElliottCRL** [Center-for-Research-Libraries/vufind#161]
Marie Waltz has sent a few emails with the "CS-576 Re: University of North Florida ILL link broken on Center for Research Libraries database" header, regarding the ILL link which is apparently not fixed. 

Placing here for visibility in case no one has seen the emails. 
She and I communicated yesterday on this topic; I can't see that there is an issue but @ryan-jacobs had said it would be deployed last Thursday.

From the email chains I've seen, by the time anyone would ask for the MilCat to be changed, they have asked several people internally, none of whom have any idea what to do.  All that time, they aren't getting any use out of their CRL membership, by the time we get it has often been weeks.

IMHO, updates to ILL links are a change that VuFind needs to be able to make and put in production, essentially, instantly.

**Comment by ryan-jacobs** [comment]
Hi @AndyElliottCRL. It sounds like there may be two topics here:

1. Verifying resolution for the recent University of North Florida ILL link update.
2. Discussing ways to improve turnaround time on future requests of this nature.

Both are of course important topics. Let's start with the first one though as ensuring that update is in place, and working, is critical. Here's the commit that addressed this ILL link update. I didn't create an issue for this as it was a very minor operational change:

https://github.com/Center-for-Research-Libraries/vufind/commit/21814b4e347aa6157aad044672b2bc392ed3d96b

This was also deployed to production that same day, or the following day, so the ILL link should have been working within 24-48 hours of the request. The parallel support@crl.edu ticket was also updated and marked as resolved on Sep 15th, which should have triggered an email status update to everyone tracking it (including you and Marie).

Can you help verify the following:

- Is the University of North Florida still reporting issues? I tested the "University of North Florida" option from the ILL picklist here with success immediately after the change was deployed: https://catalog.crl.edu/Content/access
- Did you get an email from JIRA with the notification that everything was fixed on the 15th?

I'll also check-in with Marie on this, but any info you can provide to the above will be very helpful.

**Comment by AndyElliottCRL** [comment]
Hi @ryan-jacobs 
I did get a notification last week that it was to be deployed on X date and assumed it was that simple a fix; I'm not sure in what sense it is not fixed. 
Marie raised the problem with me Monday as ""Support was supposed to fix one from North Florida last week but its still broken,".and sent a follow up email to Support Tuesday. 
Now of course, no Marie in the GitHub silo.  But maybe it's best for me not to be a middleman since I can't make any fixes. I think for the verification and workflow questions it will be best to address all that directly with Marie, since I don't have a VuFind role.

**Comment by ryan-jacobs** [comment]
Thanks @AndyElliottCRL. The verification that you got the expected JIRA (support.crl.edu) messages is helpful! If there was an issue here I would want to get it to Bing's attention ASAP.

While JIRA does not necessarily immediately route to the right implementer, it's still the place where most access question are going anyway (IP updates, etc.) and so it's easy for staff to remember. It also means we automatically get a JIRA log of what's going on. As you noted, some staff are not in Github so we need an alternative place for their needs to be logged.

As to what part of the ILL links are still broken (if any), or any problems with JIRA communication, I'll get more info from Marie and Bing on that separately. Thanks for sharing your notes!
